In [2]:
import pandas as pd

df = pd.read_csv("flipkart_data.csv")


df.columns = [col.strip().lower().replace(" ", "_") for col in df.columns]


df = df[df['actual_price'].notna()]
df = df[df['actual_price'].astype(str).str.lower() != 'n/a']


df['actual_price'] = df['actual_price'].astype(str).str.replace('₹', '', regex=False).str.replace(',', '', regex=False)
df = df[df['actual_price'] != ''] 
df['actual_price'] = df['actual_price'].astype(int)


df['offer_price'] = df['offer_price'].astype(str).str.replace('₹', '', regex=False).str.replace(',', '', regex=False).fillna('0').astype(int)


df['no.of_ratings'] = df['no.of_ratings'].astype(str).str.replace(',', '', regex=False)
df['no.of_ratings'] = pd.to_numeric(df['no.of_ratings'], errors='coerce').fillna(0).astype(int)


df['reviews'] = pd.to_numeric(df['reviews'].astype(str).str.replace(',', '', regex=False), errors='coerce').fillna(0).astype(int)

df['averager_rating'] = pd.to_numeric(df['averager_rating'], errors='coerce').fillna(0).astype(float)


df['offer_%'] = df['offer_%'].astype(str).str.replace('% off', '', regex=False).fillna('0').astype(int)


df.to_csv("flipkart_data_cleaned.csv", index=False)

In [3]:
import pandas as pd

df = pd.read_csv("flipkart_data_cleaned.csv")

columns_to_keep = [
    'product_name', 'actual_price', 'offer_price',
    'no.of_ratings', 'reviews', 'averager_rating',
    'brand', 'offer_%'
]

df_reduced = df[columns_to_keep].head(500)

df_reduced.to_csv("flipkart_data_reduced.csv", index=False)

print("Reduced dataset saved to 'flipkart_data_reduced.csv'")

Reduced dataset saved to 'flipkart_data_reduced.csv'

In [16]:
df = pd.read_csv("flipkart_data_reduced.csv")

In [18]:
df

,product_name,actual_price,offer_price,no.of_ratings,reviews,averager_rating,brand,offer_%
0,ASUS Vivobook 15 Intel Core i5 12th Gen 1235U,66990,45990,7265,408,4.2,ASUS,31
1,Acer Aspire 3 Intel Celeron Dual Core,32999,15990,923,109,3.8,Acer,51
2,Lenovo Chromebook MediaTek Kompanio 520,28690,13990,1748,160,3.8,Lenovo,51
3,SAMSUNG Galaxy Book4 Metal Intel Core i3 13th ...,57499,40990,3472,399,4.5,SAMSUNG,28
4,Infinix Y3 Max Series Intel Core i5 12th Gen 1...,69990,29990,340,65,4.3,Infinix,57
...,...,...,...,...,...,...,...,...
495,"ASUS Vivobook 16 (2025), Copilot + PC with Off...",84990,65990,41,4,4.0,ASUS,22
496,MOTOROLA Motobook 60 Full Metal Intel Core 7 (...,104890,74990,36,7,4.3,MOTOROLA,28
497,Lenovo V14 Intel Core i5 11th Gen 1135G7,63500,41000,18,1,4.2,Lenovo,35
498,DELL 15 Intel Core i3 12th Gen 1215U,44861,32990,639,45,4.2,DELL,26
499,Lenovo IdeaPad Slim 5 Co-Pilot PC Snapdragon X...,125890,54990,160,24,4.2,Lenovo,56